networks:
  outside:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: docker53
    enable_ipv6: true
    ipam:
      config:
        - subnet: 172.17.32.0/20
        - subnet: fc11:ed0:abeb:53::/64
  anycast:
    driver: macvlan
    driver_opts:
      parent: st
    enable_ipv6: true
    internal: true
    ipam:
      config:
        - subnet: 172.23.13.126/32
        - subnet: fdfd:4acc:e2:53::53/128

services:
  service:
    build: .
    cap_add:
      - NET_ADMIN
      - NET_RAW
    networks:
      outside:
        ipv4_address: 172.17.32.53
        ipv6_address: fc11:ed0:abeb:53::53
      anycast:
        ipv4_address: 172.23.13.126
        ipv6_address: fdfd:4acc:e2:53::53
